BBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXX X XXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXX
    XX XXX XXXXX XXXX XXXXXXXXXX XXX XXXX XXXXX XX
    XXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
    X
    
    XXXXXX XX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXXX
    X
    
    XXXXXX XX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXX XXXXX XXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX
    X
    
    XXXXXXXXXXX XXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXX XXXXXXXX XXXXXXX XXX XXXX XXXXX XX
    XXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXX XXXXXXXX XXX XXX XXXXX XXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXX XXXXX XXXXXXXXXXX
        XXXXXXXX XXX X XXXXXXXXXXX
        XXXXXXX X XXXXXXXXXXX
        XXXXXXXXXX XXXXX XXXXXXXXXXX
        XXXX XXXX XXXXXXXXXXX
        XXXXXX X XXXXXXXXXXX
        XXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXX XXXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX X XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX X XXXXXXXXXXX
    X
    
    XXXXXXXXX X
        XXXXXXXXX XXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXX XXXXXXXXXXXXXX X
        XXXX X
            XXXXXXXX XX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
        XX X
            XXXXXXXX XX
            XXXXXXXXXX XXXXXXXXXXXXXX
        X
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        XXXXXXXX XXXX XXXX XXXXXXXXXXX
        XXXXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXX XXXXXXXXXXX
        XXXXXXXXXXXXXX XXX XXXXXXXXXXX
        XXXXXXX XXX XXX XXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXXXX
        XXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X X
        XXXXXX XXXX XXXXXXXXXXX
        XXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXX XXXXXXXXXXX
        XXXXXXXX XXX XXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXX XXXXXXXXX XXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X X
        XXXXXXXX X XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXXXX XXX XXX XXXX XXXXX XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        XXXXXXX XXX XXXX XXXXXXXXXXX
        XXXXXXXX XXX XXXXXXXXXXX
    X
XXXXXXXX
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXX
            XXXXXXXXXX XXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XX XXX XXXXXX XX XXX XXXXXXXXXXX
        XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXX
        XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXX
                XXXX
                    XXXXXXXXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                XXXXX
            XXXXXXXX
            XXXXXXX
                BBB BBBBB BB BBBBBB
                XXXX
                    XXXXXXXXX
                    XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF
                        XXXX
                    XXXXX
                    XXXXFFFFFFFFFFFFFFFFFXXXXX
                    XXXXXXXXX
                    XXXXFFFFFFFFFFFFFFFFFXXXXX
                    XXXXXXXXX
                    XXXX
                        BB BBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX FFFFFFFFFFFFFXXXXXXX
                        BBBB
                            XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BBBBB
                    XXXXX
                    XXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                X
                            XXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX
                                        XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX
                                    XXXX
                                XXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBXX
                                        XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX
                                    XXXX
                                XXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX
                                        XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXX
                                    XXXX
                                XXXXX
                            XXXXX
                        XXXXXX
                    XXXXX
                XXXXX
                BBBBB
                XXXX
                    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
                XXXXX
                BBBBBB
            XXXXXXXX
        XXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBB

            XXXXXXXXXX  XX XXXXXXX

            BB BBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BBBBB
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
