BBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXX X XXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXX
    XX XXX XXXXX XXXX XXXXXXXXXX XXX XXXX XXXXX XX
    XXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
    X
    
    XXXXXX XX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXXX
    X
    
    XXXXXX XX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXX XXXXX XXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXX XXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXX XXXXXXXX XXXXXXX XXX XXXX XXXXX XX
    XXXXXXXXX X
        XXXXXXXXX XXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXX XXXXXXXX XXX XXX XXXXX XXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXX XXXXX XXXXXXXXXXX
        XXXXXXXX XXX X XXXXXXXXXXX
        XXXXXXX X XXXXXXXXXXX
        XXXXXXXXXX XXXXX XXXXXXXXXXX
        XXXX XXXX XXXXXXXXXXX
        XXXXXX X XXXXXXXXXXX
        XXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXX XXXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX X XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX X XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        XXXXXXXX XXXX XXXX XXXXXXXXXXX
        XXXXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXX XXXXXXXXXXX
        XXXXXXXXXXXXXX XXX XXXXXXXXXXX
        XXXXXXX XXX XXX XXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXXXX
        XXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X X
        XXXXXX XXXX XXXXXXXXXXX
        XXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXX XXXXXXXXXXX
        XXXXXXXX XXX XXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXX XXXXXXXXX XXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X X
        XXXXXXXX X XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX XXX XXXXXXXXX XXX XXX XXXX XXXXX XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        XXXXXXX XXX XXXX XXXXXXXXXXX
        XXXXXXXX XXX XXXXXXXXXXX
    X
XXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXX XXXXXXXXXX
    XX XXXXXXXXXXXXXXXXX XX XXX XXXXX XX XXX XXXXXXXXXXX

        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXX
                XXXX
                    XXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                XXXXX
            XXXXXXXX
            XXXXXXX
                BBB BBBB BB BBBBB
                XXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXFFFFFFF FF FFXXXXX
                    XXXXXXXXX
                    XXXXBB BBBBBBBBBBBBBBBFFFFFFFFFFFFFBBBBXXXBBBBBXXXXX
                    XXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                X
                            XXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBXX
                                        XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX
                                    XXXX
                                XXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBXX
                                        XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXX
                                    XXXX
                                XXXXX
                            XXXXX
                        XXXXXX
                    XXXXX
                XXXXX
                BBBBB
                XXXX
                    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                XXXXX
                BBBBBB
            XXXXXXXX
        XXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBB

            XXXXXXXXXX  XX XXXXXXX

            BB BBBBBBBBBBBBBB
            XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BBBBB
        XXXXXX
XXXXXX
BBBBBBBB
