BBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXX XXXXX X BBBBBBBB

BBBBB BBBBBBB
XXXXXXX
    XXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXX XXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXX XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXX XXXX XX
    X
    
    XXXXXXXXXXX XX X
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXX X X
        XXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXX XXXXXX X
        XXXXXX XXXXXXXX
    X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
                XXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXX
                XXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXX XX XXXXXXXXXXX XXXXXX XXXX XXXXXX XXXX XXXXXX XXXXXX XX XXXXXXX
                        XXX XXXXXXX XXX XXXXXXX XXX XXXX XXXXX XXXX XXXX XX XXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFXXXX
                        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFXXXX
                        BB BBBBBBBBBBBBBBBBB
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFXXXX
                        BBBBB
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                            BB BBBBBBBBBBBBBB
                                 XXXXXXX
                            BBBB
                                XXXXXXX
                            BBBBB
                        XXXX
                    XXXXXX

                    XXXXX XXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX
                                XX XXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXX XXX XXXX XX XXXXXX XXXXXXX
                            XXXXXX
                            XXXXX
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                                    XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                                XXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                                    XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXX
                                XXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
