BBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXX XXXX X BBBBBBBB

BBBBB BBBBBBB
XXXXXXX
    XX XXX XXXX XXXX XXXXXXXXXX XXX XXXX XXXXX XX
    XXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX X X X XXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXXXX
                    XXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                XXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXX
                XXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX
                        BBBBBBBBBB
                        
                        XXXX XXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXX
                                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX

                            XXXX XXXXXXXXXXXXXXX XXXXXX
                                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                        XXXXX XXXXXX
                                    XXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXX XXX XXX XXXX XXX XXXXX XXXXXXXXXXX
                                XXXXXX
                            XXXXXX

                            XXXX XXXXXXXXXXXXXXX XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                        XXXXXX
                                    XXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXX XX XXXXXXX XX XXXXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX FFFFFFF FF FFXXXX
                                XXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBFFFFFFF FF F FFFFBBBBXXXXXBBBBB
                            XXXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                                XX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX
                            XXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
