BBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXX XXXXX X BBBBBBBB

BBBBB BBBBBBB
XXXXXXX
    XX XXX XXXX XXXX XXXXXXXXXX XXX XXXX XXXXX XX
    XXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX X X X XXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXXXX
                    XXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                XXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXX
                XXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX
                        BBBBBBBBBB
                        
                        XXXX XXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXX
                                XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX

                            XXXX XXXXXXXXXXXXXXX XXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX
                            XXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX
                            XXXXXX

                            XXXX XXXXXXXXXXXXXXX XXXXXX
                                XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
                            XXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                                XX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
                            XXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
