BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBXXX XXXXXX X XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXX
    XX XXXXXXXX XXXXXX XXXXXXX XX
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXX XXXXXXXX XXX XXX XXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXX XXXXXX
        XXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXX XXXXXXXX XXX XXX XXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXX XX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXX
        XXXXXX XXXXX
        XXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXXXXXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXX
        XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XX XXXX XXX
    X
    
    XXXXXXXXXX XXXXXXXXX X
        XXXX X 
            XXXXXXXX XX 
            XXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XX
        X
        XX X 
            XXXXXXXX XX 
            XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXX
        X
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX XX
    X
    
    XXXXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXX X XXX XXXX XXXXXXX XX XX XXXX XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
    X
    
    XXXXXXXXXXXX XXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXXX XXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXX
    X
    
    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXX XXXXXXXXX XXX XXXX XXXX XXXXXX
        XXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXX XXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXX XXXXXXXXX XXX XXXX XXXX XXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXX
        XXXXXX XXXX
        XXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XX
    X
    
    XX XXXXXXXXXX XXXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXX XXXXX
        X
        
        XXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXX
        X
    X
    
    XX XXXXX XXXXXXXX XXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXX
        XXXXXXXXX XXXXXXXXX
        XXXX XX
        XXXXX XX
        XXXXXX XX
        XXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXXX XX
    X
XXXXXXXX

XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX gettext(u'All Movies') XXXXX
        XX XXXXXXXXXXXXX gettext(u'Discover and rate your favorite movies') XXXX
    XXXXXX
XXXXXX

XXXX XXXXXXX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXXXX XXX XXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXX gettext(u'Filters & Sort') XXXXXXX
        XXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Genre') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXX gettext(u'All Genres') XXXXXXXXX
                            BBB BBBBB BB BBBBBBBBBB
                                XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX
                                    
                                XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Year') XXXXXXXX
                        XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXX gettext(u'Any Year') XXXXXXXXX
                            BBB BBBB BB BBBBBBBBB
                                XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                                    
                                XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Director') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXX gettext(u'Any Director') XXXXXXXXX
                            BBB BBBBBBBB BB BBBBBBBBBBBBB
                                XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                                    
                                XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Min Rating') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXX gettext(u'Any Rating') XXXXXXXXX
                            XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'4+ Stars') XXXXXXXXX
                            XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'3+ Stars') XXXXXXXXX
                            XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'2+ Stars') XXXXXXXXX
                            XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX gettext(u'1+ Stars') XXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Sort By') XXXXXXXX
                        XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXXXBBBBBX gettext(u'Title A-Z') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Release Year (Newest)') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Release Year (Oldest)') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Highest Rated') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Lowest Rated') XXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Apply Filters') 
                XXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Clear All') 
                XXXX
            XXXXXX
        XXXXXXX
        
        XXXX XXXXXX XXXXXXX XXXXXXX XXX
        BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Active Filters') XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                BB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Stars') XXXXXXXBBBBB
            XXXXXX
        XXXXXX
        BBBBB
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXX
    BBB BBBBB BB BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBB
                        XXXX XXXXXX XXXXXXX
                    BBBB BBBBBBBBBBBB
                        XXXX XXXXXX XXXXXXX
                    BBBB
                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'No Image') XXXXXXX
                        XXXXXX
                    BBBBB
                XXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXX
                            XXXXXXFFFFFFFFFFFFFXXXXXXX
                        XXXXXX
                    BBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXX
                        XXXXXX
                    BBBBB
                    XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'View Details') XXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXX gettext(u'Rate') XXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XXXX gettext(u'No movies available') XXXXX
            XXX gettext(u'There are no movies in the database yet. Check back later!') XXXX
        XXXXXX
    XXXXXX
    BBBBBB
XXXXXX

BB BBBBBB
XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXBBBBBXXXXXXX gettext(u'Previous') XXXX
                XXXXX
                BBBBB
                
                BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBB BB BBB
                XXX XXXXXXXXXXXXXXXX XXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                BBBB BBB B BBBBBBBBBBBBBBBBBBBBBB BBB BBB B BBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXBBBBBXXXXXXXXXXX
                XXXXX
                BBBBB
                BBBBBB
                
                BB BBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXBBBBBXXXXXXX gettext(u'Next') XXXX
                XXXXX
                BBBBB
            XXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBB

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXX XX XXXXXXX XXXXXX XXXX
        XXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX X X gettext(u'Filters & Sort') XX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXX XX XXXXXX XXXXXX XXXX
        XXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX X X gettext(u'Hide Filters') XX
    X
X

XX XXXX XXXXXXX XX XXXXXXX XX XXX XXXXXXX XXX XXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXXXX X BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBXXXXBBBBXXXXXBBBBBX
    
    XX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXX
    X
    
    XX XXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XX XXX XXXXXX XXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
    XXX
    
    XX XXX XXXXXX XXXXXX XX XXXXXX XXXX XXXXXXX XXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                XXXXXXXXX XXXXXXXXX
                XXXXXX XXXXXXX 
            XXX
        XX XXXXX
    X
XXX
XXXXXXXXX
BBBBBBBB
