BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB X XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBB
            XXXX XXXXXX XXXXXXXXXXX XX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX
        BBBB BBBBBBBBBBBB
            XXXX XXXXXX XXXXXXXXXXX XX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX
        BBBB
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX
                 gettext(u'No Image Available') 
            XXXXXX
        BBBBB

    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XX XXXXXXXXXXXXXXXXX
        
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX gettext(u'Movie Details') XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX gettext(u'Director') XXXXXXXXXX XXXXX
                    XXXXXXXXXXXX gettext(u'Release Year') XXXXXXXXXX XXXXX
                    XXXXXXXXXXXX gettext(u'Genre') XXXXXXXXXX XXXXX
                    XXXXXXXXXXXX gettext(u'Duration') XXXXXXXXXX   gettext(u'minutes') XXXXX
                XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX gettext(u'Ratings') XXXXX
                BB BBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX FFFFFFFFFFFFFXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX  ngettext(u'rating', u'ratings', count) SSSSSSPPPPPPPXXXXXXXXX
                XXXXXX
                BBBB
                XX XXXXXXXXXXXXXXXXXXX gettext(u'No ratings yet') XXXX
                BBBBB
                
                BB BBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Rate This Movie') XXXX
                BBBB
                XX XXXXXXBBB BBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Login to Rate') XXXX
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXX gettext(u'User Reviews') XXXXX
        BB BBBBBBB
        BBB BBBBBB BB BBBBBBB
        XXXX XXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFF FF FFXXXXXXXX
                    XXXXXX
                XXXXXX
                BB BBBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
        XXXXXX
        BBBBBB
        BBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XXX gettext(u'No reviews yet. Be the first to review this movie!') XXXX
        XXXXXX
        BBBBB
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Back to All Movies') XXXX
    XXXXXX
XXXXXX
BBBBBBBB
